"""Markdown report generator for witness log sessions.

Generates GitHub / Zenn / Qiita-compatible Markdown.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import agentwit
from agentwit.witness.chain import ChainManager


class MarkdownReporter:
    """Generate a Markdown-formatted audit report from a witness log session."""

    def __init__(self, session_dir: Path) -> None:
        self.session_dir = Path(session_dir)

    def load_events(self) -> list[dict]:
        """Read all events from ``witness.jsonl``."""
        jsonl = self.session_dir / "witness.jsonl"
        events: list[dict] = []
        with open(jsonl, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    events.append(json.loads(line))
        return events

    def generate(self) -> str:
        """Build and return the Markdown report string."""
        events = self.load_events()
        session_id = self.session_dir.name
        generated_at = datetime.utcnow().isoformat(timespec="seconds") + "Z"
        actor = events[0].get("actor", "unknown") if events else "unknown"
        total_events = len(events)

        # Chain verification
        chain = ChainManager(session_id=session_id)
        if events:
            verify_results = chain.verify_chain(events)
            chain_valid = all(r["valid"] for r in verify_results)
        else:
            verify_results = []
            chain_valid = True

        integrity_label = "✅ VALID" if chain_valid else "❌ TAMPERED"

        # Risk counts (by worst severity per event)
        from agentwit.analyzer.scorer import RiskScorer

        scorer = RiskScorer()
        risk_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
        all_patterns: dict[str, int] = {}

        annotated: list[tuple[dict, list[dict], str]] = []
        for event in events:
            indicators = event.get("risk_indicators") or scorer.score_event(event)
            worst = _worst_severity(indicators)
            if worst in risk_counts:
                risk_counts[worst] += 1
            for ri in indicators:
                pat = ri.get("pattern", "")
                all_patterns[pat] = all_patterns.get(pat, 0) + 1
            annotated.append((event, indicators, worst))

        high_risk_count = risk_counts["critical"] + risk_counts["high"]

        lines: list[str] = []

        # Header
        lines += [
            f"# Witness Report: {session_id}",
            "",
            f"> Generated by **agentwit v{agentwit.__version__}** on {generated_at}",
            "",
        ]

        # Summary
        lines += [
            "## Summary",
            "",
            f"| Key | Value |",
            f"|-----|-------|",
            f"| Session ID | `{session_id}` |",
            f"| Actor | `{actor}` |",
            f"| Generated At | {generated_at} |",
            f"| Chain Integrity | {integrity_label} |",
            f"| Total Events | {total_events} |",
            f"| High Risk Events | {high_risk_count} |",
            "",
        ]

        # Risk Indicators table
        lines += [
            "## Risk Indicators",
            "",
            "| Severity | Count |",
            "|----------|-------|",
            f"| 🔴 CRITICAL | {risk_counts['critical']} |",
            f"| 🟠 HIGH | {risk_counts['high']} |",
            f"| 🟡 MEDIUM | {risk_counts['medium']} |",
            f"| 🟢 LOW | {risk_counts['low']} |",
            "",
        ]

        if all_patterns:
            lines += [
                "### Pattern Frequency",
                "",
                "| Pattern | Hits |",
                "|---------|------|",
            ]
            for pat, cnt in sorted(all_patterns.items(), key=lambda x: -x[1]):
                lines.append(f"| `{pat}` | {cnt} |")
            lines.append("")

        # Event Timeline
        lines += [
            "## Event Timeline",
            "",
            "| # | Timestamp | Action | Tool | Risk |",
            "|---|-----------|--------|------|------|",
        ]
        for event, indicators, worst in annotated:
            idx = event.get("index", "")
            ts = event.get("timestamp", "")[:19]  # trim microseconds
            action = event.get("action", "")
            tool = event.get("tool", "") or "-"
            if indicators:
                sev_icons = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}
                icon = sev_icons.get(worst, "")
                risk_cell = icon + " " + ", ".join(
                    f"`{ri['pattern']}`" for ri in indicators
                )
            else:
                risk_cell = "—"
            lines.append(f"| {idx} | {ts} | `{action}` | `{tool}` | {risk_cell} |")

        lines.append("")

        # Chain Verification
        lines += [
            "## Chain Verification",
            "",
        ]
        if chain_valid:
            lines += [
                "✅ **Chain integrity verified.** All cryptographic hashes are consistent.",
                "No evidence of log tampering detected.",
                "",
            ]
        else:
            lines += [
                "❌ **Chain integrity check FAILED.**",
                "The following events have broken hash chains:",
                "",
            ]
            for r in verify_results:
                if not r["valid"]:
                    lines.append(f"- Event `{r['index']}`: {r['reason']}")
            lines.append("")

        # Footer
        lines += [
            "---",
            "",
            f"*Generated by [agentwit](https://github.com/tokotokokame/agentwit) v{agentwit.__version__}*",
            "",
        ]

        return "\n".join(lines)

    def render(self) -> str:
        return self.generate()


def _worst_severity(indicators: list[dict]) -> str:
    order = {"low": 0, "medium": 1, "high": 2, "critical": 3}
    worst = ""
    for ri in indicators:
        sev = ri.get("severity", "low")
        if order.get(sev, 0) > order.get(worst, -1):
            worst = sev
    return worst or ""
